import type { Comparable } from '@/features/comparables/types';

// Shared Comparable factory for the analysis tests. Retained + priced + surfaced
// by default; override any field per scenario.
export function makeComparable(overrides: Partial<Comparable> = {}): Comparable {
  return {
    id: overrides.id ?? Math.random().toString(36).slice(2),
    agency_id: 'agency',
    project_id: 'project',
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
    display_order: 0,
    is_selected: true,
    title: 'Bien',
    address: null,
    postal_code: null,
    city: 'Antibes',
    district: null,
    surface_area: 50,
    land_area: null,
    property_type: null,
    rooms_count: null,
    bedrooms_count: null,
    bathrooms_count: null,
    energy_rating: null,
    ges_rating: null,
    construction_year: null,
    heating_type: null,
    energy_source: null,
    source: null,
    sold_by: null,
    sold_by_source: null,
    exclusivity: null,
    exclusivity_source: null,
    listing_published_at: null,
    listing_url: null,
    locator_address: null,
    locator_analyzed_at: null,
    locator_confirmed: null,
    locator_label: null,
    locator_label_key: null,
    locator_latitude: null,
    locator_longitude: null,
    locator_property_id: null,
    locator_source: null,
    locator_state: null,
    prospecting_handed_at: null,
    prospecting_meeting_at: null,
    prospecting_mandate_at: null,
    prospecting_declined_at: null,
    listing_description: null,
    listing_features: [],
    photo_urls: [],
    portal_price_per_square_meter: null,
    price: 250000,
    days_on_market: null,
    price_drop_amount: null,
    price_drop_percentage: null,
    advisor_notes: null,
    general_condition: null,
    exposure: null,
    outdoor_spaces: [],
    parking_types: [],
    ...overrides,
  };
}
